conceptsandtraining/doil

README.md, src/lib/instances/create/create.sh, src/lib/instances/delete/delete.sh, src/lib/instances/repair/repair.sh
=> Fixed comunication between salt server

CHANGELOG.md, src/lib/instances/repair/repair.sh, src/lib/repo/add/add.sh
=> Fixed repo:add and typos

src/tpl/minion/docker-compose-mac.yml, src/tpl/minion/docker-compose.yml
=> #47 Implemented SSH Key for private repositories

src/tpl/minion/docker-compose.yml
=> #35 Implemented persistent configuration directories for apache, mysql and php

src/tpl/stack/states/php7.0/php/init.sls, src/tpl/stack/states/php7.1/php/init.sls, src/tpl/stack/states/php7.2/php/init.sls, src/tpl/stack/states/php7.3/php/init.sls, src/tpl/stack/states/php7.4/php/init.sls, src/tpl/stack/states/php8.0/php/init.sls
=> #61 Implemented missing php modules

src/lib/instances/delete/delete.sh, update.sh
=> #59 doil rm now deletes salt key

src/tpl/proxy/conf/local.conf
=> #71 increased timeout

src/lib/system/salt/salt.sh, src/tpl/stack/states/base/apache/default, src/tpl/stack/states/dev/devtools/init.sls, update.sh
=> #66 moved adminer out of docroot

src/lib/instances/create/create.sh, src/tpl/minion/Dockerfile
=> Implemented fix for user permissions on files

src/lib/pack/export/export.sh, src/lib/pack/export/help.sh, src/lib/pack/help.sh, src/lib/pack/import/help.sh, src/lib/pack/import/import.sh, src/lib/pack/pack.sh
=> Implemented doil pack

src/tpl/minion/docker-compose-mac.yml, src/tpl/minion/docker-compose.yml, src/tpl/proxy/service-config.tpl, src/tpl/stack/states/autoinstall/autoinstall/config-replace.sh, src/tpl/stack/states/autoinstall/autoinstall/init.sls, src/tpl/stack/states/base/apache/apache-config-replace.sh, src/tpl/stack/states/base/apache/default, src/tpl/stack/states/base/apache/init.sls
=> Implemented dynamic http path inside of proxy, apache and ilias

src/lib/system/salt/help.sh, src/lib/system/salt/salt.sh
=> #96 Implemented list of available states

src/lib/instances/create/create.sh, src/stack/states/ilias/ilCron/init.sls, src/templates/minion/README.md
=> #103 Implemented correct behaviour for cron, also fixes #101

src/stack/states/ilias/ilServer/ilServer.ini, src/stack/states/ilias/ilServer/init.sls
=> #102 Adjusted server configuration

src/lib/include/aliases.sh, src/lib/instances/processstatus/help.sh, src/lib/instances/processstatus/processstatus.sh
=> #106 Implemented processstatus

README.md
=> #105 added quickstart

update.sh
=> For #100 updated update.sh

CHANGELOG.md, README.md, install.sh, src/lib/help.sh, src/lib/instances/create/create.sh, src/lib/instances/delete/delete.sh, src/lib/pack/export/export.sh, src/lib/pack/import/import.sh, src/lib/system/version/version.sh, src/stack/states/dev/devtools/githook-post-merge, src/templates/minion/docker-compose.yml, update.sh
There are some small fixes for windows, but main part is #122
=> Implemented windows compatibility, fixed doil pack

src/server/proxy/docker-compose.yml
=> #141 Exposed proxy ports

src/lib/pack/import/import.sh
=> #144 Increased sleep time in importer

src/lib/instances/create/create.sh, src/lib/instances/up/up.sh, src/server/proxy/conf/local.conf, src/stack/states/php7.0/php/init.sls, src/stack/states/php7.1/php/init.sls, src/stack/states/php7.2/php/init.sls, src/stack/states/php7.3/php/init.sls, src/stack/states/php7.4/php/init.sls, src/stack/states/php8.0/php/init.sls
=> #134 Icreaded upload limit

src/lib/instances/delete/delete.sh
=> #145 Fixed deletion

src/lib/instances/create/create.sh
=> #135 Implemented fix for repo schenanigans

src/lib/include/system.sh
=> #164 Implemented fix for installation

src/lib/include/aliases.sh
=> #171 fixed aliases with using path to doil

src/lib/include/system.sh
=> #164 added installation fix

src/lib/instances/create/create.sh
=> #168 Implemented fallback for -r if repository couldnt be found

src/lib/instances/up/up.sh
=> #163 Fixed host in up message

src/lib/include/helper.sh, src/lib/instances/apply/apply.sh, src/lib/instances/create/create.sh, src/lib/instances/delete/delete.sh, src/lib/instances/down/down.sh, src/lib/instances/login/login.sh, src/lib/instances/up/up.sh, src/lib/pack/export/export.sh, src/lib/pack/import/import.sh, src/lib/system/deinstall/deinstall.sh, src/lib/system/proxy/proxy.sh, src/lib/system/salt/salt.sh
=> #171 adjusted path over whole project

app/src/Commands/Salt/RestartCommand.php, app/src/Commands/Salt/UpCommand.php, app/tests/Commands/Salt/RestartCommandTest.php, app/tests/Commands/Salt/UpCommandTest.php, setup/stack/states/proxyservices/proxyservices/sv-nginx.conf, setup/templates/proxy/conf/salt-startup.sh, setup/templates/proxy/conf/startup.conf
https://github.com/conceptsandtraining/doil/issues/237
=> master states/templates: 237 nginx now starts with supervisor

README.md
https://github.com/conceptsandtraining/doil/issues/236
=> master readme: 236 adjust old doil commands

setup/checks.sh, setup/install.sh
https://github.com/conceptsandtraining/doil/issues/235
=> master install: 235 add port check

setup/checks.sh, setup/install.sh, setup/system.sh
https://github.com/conceptsandtraining/doil/issues/234
=> master install: 234 add requirement check if user is in doil group

setup/system.sh
https://github.com/conceptsandtraining/doil/issues/240
=> master install: 240 allow composer to run as super user

README.md
https://github.com/conceptsandtraining/doil/issues/241
=> master readme: 241 make it clear wich parameter is for name and which for branch

README.md, app/src/Commands/Instances/ExecCommand.php, app/src/Lib/Docker/Docker.php, app/src/Lib/Docker/DockerShell.php, app/src/cli.php
https://github.com/conceptsandtraining/doil/issues/210
=> feature_release commands:210 add new command 'exec'

setup/doil.sh
https://github.com/conceptsandtraining/doil/issues/255
=> feature_release setup:255 quote params given to cli

README.md, app/src/Commands/System/UninstallCommand.php, app/src/Lib/Docker/DockerShell.php, app/tests/Commands/System/UninstallCommandTest.php, setup/system.sh
https://github.com/conceptsandtraining/doil/issues/226
=> feature_release commands:226 add prune parameter to uninstall

README.md, app/src/Commands/Instances/CreateCommand.php, setup/stack/config/master.cnf, setup/stack/states/disable-xdebug/top.sls, setup/stack/states/disable-xdebug/xdebug/init.sls, setup/stack/states/enable-xdebug/top.sls, setup/stack/states/enable-xdebug/xdebug/init.sls
https://github.com/conceptsandtraining/doil/issues/167
=> feature_release states:167 add states to en/disable xdebug; also add a flag '-x' to install xdebug on instance creation

setup/stack/states/php7.2/php/init.sls, setup/stack/states/php7.3/php/init.sls, setup/stack/states/php7.4/php/init.sls, setup/stack/states/php8.0/php/init.sls, setup/stack/states/php8.1/php/init.sls
https://github.com/conceptsandtraining/doil/issues/257
=> feature_release saltstack:257 add a missing refresh flag to pck.installed

setup/stack/states/php7.0/php/init.sls, setup/stack/states/php7.1/php/init.sls, setup/stack/states/php7.2/php/init.sls, setup/stack/states/php7.3/php/init.sls, setup/stack/states/php7.4/php/init.sls, setup/stack/states/php8.0/php/init.sls
https://github.com/conceptsandtraining/doil/issues/262
=> master states:262 change php states to install also base package and enable php on cli

README.md, app/src/Commands/Instances/ApplyCommand.php, app/src/Commands/Mail/ChangePasswordCommand.php, app/src/Lib/Docker/Docker.php, app/src/Lib/Docker/DockerShell.php, app/src/cli.php, app/tests/Commands/Mail/ChangePasswordCommandTest.php, setup/stack/config/master.cnf, setup/stack/states/change-roundcube-password/change-roundcube-password/init.sls, setup/stack/states/change-roundcube-password/top.sls
https://github.com/conceptsandtraining/doil/issues/231
=> feature_release mail:231 add state and command to change roundcube password

setup/checks.sh, setup/install.sh
https://github.com/conceptsandtraining/doil/issues/269
=> master install:269 add a check for .ssh folder

setup/templates/mail/Dockerfile, setup/templates/minion/Dockerfile, setup/templates/proxy/Dockerfile, setup/templates/salt/Dockerfile
https://github.com/conceptsandtraining/doil/issues/268
=> feature_release templates:268 add nano to Dockerfile

setup/stack/states/php7.2/php/init.sls, setup/stack/states/php7.3/php/init.sls, setup/stack/states/php7.4/php/init.sls, setup/stack/states/php8.0/php/init.sls, setup/stack/states/php8.1/php/init.sls
https://github.com/conceptsandtraining/doil/issues/273
=> feature_release states:273 set max_execution_time for php inis to 3600

README.md, setup/conf/doil.conf, setup/helper.sh, setup/install.sh, setup/system.sh
https://github.com/conceptsandtraining/doil/issues/267
=> feature_release setup:267 set a mail password via doil.conf

.github/CONTRIBUTING.md, .github/TESTING.md
https://github.com/conceptsandtraining/doil/issues/277
=> feature_release documentation:277 adjust contibuting and testing files

app/src/Commands/Pack/ExportCommand.php, app/src/Commands/Pack/ImportCommand.php
https://github.com/conceptsandtraining/doil/issues/281
=> feature_release pack:281 adjust regex for instance names

app/src/Commands/Pack/ExportCommand.php
https://github.com/conceptsandtraining/doil/issues/282
=> feature_release pack:282 implement confirmation before overwriting a file

app/src/Commands/User/DeleteCommand.php, app/tests/Commands/User/DeleteCommandTest.php
https://github.com/conceptsandtraining/doil/issues/288
=> feature_release user:288 implement acknowledgement confirmation

setup/helper.sh
Because I like to test unusual things ;)
=> Feature release: Small fix for a very unlikely error message during update

setup/stack/states/ilias-postinstall/devmode/init.sls
https://github.com/conceptsandtraining/doil/issues/287
=> feature_release state/ilias_postinstall:287 add property 'ignore_if_missing' for ilias without auotinstaller

app/src/Commands/Instances/CreateCommand.php, setup/stack/config/master.cnf, setup/stack/states/access/access/init.sls, setup/stack/states/nodejs/nodejs/init.sls, setup/stack/states/nodejs/top.sls, setup/stack/states/php7.2/php/init.sls, setup/stack/states/php7.3/php/init.sls, setup/stack/states/php7.4/php/init.sls, setup/stack/states/php8.0/php/init.sls, setup/stack/states/php8.1/php/init.sls, setup/stack/states/php8.2/php/init.sls
https://github.com/conceptsandtraining/doil/issues/308
=> frh states:308 add node state for ilias instances >= 9

app/src/App.php, app/src/Commands/Instances/CreateCommand.php, setup/templates/mail/Dockerfile, setup/templates/proxy/Dockerfile, setup/templates/salt/Dockerfile, setup/updates/update-20230329.sh
https://github.com/conceptsandtraining/doil/issues/321
=> frh Dockerfiles:321 fix apt calls

setup/templates/base/Dockerfile
https://github.com/conceptsandtraining/doil/issues/342
=> dic template:342 add wkhtmltopdf to the apt install list for base dockerfile

app/src/Commands/Instances/CreateCommand.php, app/tests/Commands/Instances/CreateCommandTest.php, setup/stack/states/ilias/ilCron/ilias_cron_9.sh, setup/stack/states/ilias/ilCron/init.sls
https://github.com/conceptsandtraining/doil/issues/341
=> dic states:341 extend cron state to handle ILIAS 9 cron jobs

setup/system.sh, setup/templates/mail/conf/salt-startup.sh, setup/uninstall.sh
=> master uninstall: also remove all doil artifacts with param --not-all

README.md, app/src/Commands/Instances/CreateCommand.php, app/src/Commands/Pack/ExportCommand.php, app/src/Commands/Pack/ImportCommand.php, app/src/Lib/Docker/DockerShell.php, app/src/Lib/SymfonyShell.php, setup/doil.sh, setup/stack/states/autoinstall/autoinstall/ilias-config.json, setup/templates/minion/docker-compose.yml
Der mysql Part wurde wieder mit reingenommen. Beim import wird der doch benötigt.
Https ist per default erstmal aus.
=> fmui export: 392 enable doil to start export by cron

README.md
=> master README: add known problems to README

app/src/App.php, app/src/Commands/Instances/CreateCommand.php, app/src/Commands/Pack/PackCreateCommand.php, setup/stack/states/autoinstall/autoinstall/init.sls, setup/stack/states/base/mysql/init.sls, setup/stack/states/ilias/ilCron/init.sls, setup/system.sh, setup/updates/update-20240801.sh
If you have already reinstall 'doil' for the last patch '20240730' only run 'sudo setup/update.sh'.
Otherwise follow the steps descriped for patch '20240730' and reinstall 'doil'
=> master hotfix: fix problems with the ILIAS database password

app/src/App.php, app/src/Commands/Instances/SetUpdateTokenCommand.php, setup/stack/states/ilias-update-hook/ilias-update-hook/update_hook.php.j2, setup/updates/update-20250523.sh
commit after setting update token
=> master ilias-update-hook: add logging to update_hook.php.j2

app/src/Commands/Pack/ImportCommand.php, app/src/Lib/FileSystem/FilesystemShell.php, app/tests/Commands/Pack/ImportCommandTest.php
JSON-Flags:
JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT
=> master pack:import: create ilias-config.json with correct JSON flags and change the instance name
